# Generated by Django 5.0.9 on 2024-09-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bamboos',
            field=models.IntegerField(default=0),
        ),
    ]
