# Generated by Django 5.0.9 on 2024-09-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_userinfo_bamboos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.IntegerField()),
                ('next_campus', models.IntegerField()),
            ],
        ),
    ]
