# Generated by Django 5.0.9 on 2024-09-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='campus',
            field=models.IntegerField(unique=True),
        ),
    ]
