# Generated by Django 5.0.9 on 2024-09-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_pair_delete_campus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pair',
            name='user1',
            field=models.CharField(max_length=100000),
        ),
        migrations.RemoveField(
            model_name='pair',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='user2',
        ),
    ]
