# Generated by Django 5.0.9 on 2024-09-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_pair_unique_together_alter_pair_user1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='user1',
        ),
        migrations.AddField(
            model_name='pair',
            name='users',
            field=models.CharField(default='null', max_length=10000),
        ),
    ]
