# Generated by Django 5.0.9 on 2024-09-27 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_pair_user1_pair_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddField(
            model_name='pair',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pair',
            name='user1',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pair',
            name='user2',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pair',
            name='users',
        ),
    ]
