# Generated by Django 5.0.9 on 2024-09-27 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_pair_updated_at_alter_pair_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='user1',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pair',
            name='user2',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
