# Generated by Django 5.0.9 on 2024-09-27 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_pair_user1_alter_pair_user2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.DeleteModel(
            name='Pair',
        ),
    ]
