# Generated by Django 5.0.9 on 2024-09-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderHandler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
